# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  #fileSystems."/" =
  #  { device = "tmpfs";
  #    fsType = "tmpfs";
  #  };

  #fileSystems."/nix" =
  #  { device = "/dev/disk/by-uuid/a90b12be-b66f-41e7-850f-c491e42ec3b8";
  #    fsType = "btrfs";
  #    options = [ "subvol=@nix" ];
  #  };

  #fileSystems."/persist" =
  #  { device = "/dev/disk/by-uuid/a90b12be-b66f-41e7-850f-c491e42ec3b8";
  #    fsType = "btrfs";
  #    options = [ "subvol=@persist" ];
  #  };

  #fileSystems."/boot" =
  #  { device = "/dev/disk/by-uuid/FC61-D837";
  #    fsType = "vfat";
  #    options = [ "fmask=0022" "dmask=0022" ];
  #  };

  #swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
